version: '3.8'

services:
  app:
    image: cduarte/parcial2-cars:latest
    container_name: app-1
    ports:
      - "8080:8080"
    depends_on:
      - mariadb
    networks:
      - parcial2-network
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/parcial2db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=parcial2db
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - parcial2-network
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

networks:
  parcial2-network:
    driver: bridge

volumes:
  mariadb-data: